---
- name: Deploy as3 declaration
  hosts: localhost
  connection: local
  gather_facts: false
  
 
  vars:
    uri_method: "POST"
  vars_files:
    - ../creds/bigip_creds.yaml

  tasks:

    - name: Send AS3 declartion
      uri:
        url: https://51.142.10.142:8443/mgmt/shared/appsvcs/declare?show=full
        user: "{{bigip_user}}"
        password: "{{bigip_pass}}"
        method: "{{uri_method}}"
        body: "{{ lookup('file','as3-declaration-1.json') }}"
        force_basic_auth: yes
        status_code: 200
        body_format: json
        validate_certs: False
      register: as_output
    - name: Print the result  
      debug:
        msg: "The resul is {{as_output}}"
...